version: "3.8"

services:
  gpmil-web:
    container_name: gpmil
    restart: always
    build:
      context: .docker/local
      dockerfile: DockerFile
      args:
        WWWGROUP: '1000'
    ports:
      - "8000:80"
    environment:
      WWWUSER: '1000'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - sail

  db:
    container_name: euz-db
    image: mysql:latest
    restart: always # command: "mysqld --init-file docker/db/init.sql"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_DATABASE: "gpmil"
      # MYSQL_USER: "gpmil"
      # MYSQL_PASSWORD: "gpmil"
    ports:
      - "3306:3306"
    networks:
      - sail

  pma:
    image: phpmyadmin:latest
    container_name: euz-pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "root"
      UPLOAD_LIMIT: 128M
      PMA_ARBITRARY: 1
    ports:
      - 8001:80
    links:
      - db:db
    networks:
      - sail

networks:
  sail:
    driver: bridge
volumes:
  redis:
    driver: local
  db:
