FROM php:8.2-apache

# Imagem-Base:INICIO

WORKDIR /var/www/html

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=Brazil/East

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y \
    && apt-get install -y locales libpng-dev libxslt-dev libmcrypt-dev zlib1g-dev libonig-dev libcurl3-openssl-dev git ca-certificates build-essential libzip-dev \
    # locale
    && localedef -i pt_BR -c -f UTF-8 -A /usr/share/locale/locale.alias pt_BR.UTF-8 \
    # clean apt
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pear config-set http_proxy ""
RUN pecl install redis-6.0.2
RUN rm -rf /tmp/pear
RUN docker-php-ext-enable redis

ENV LANG pt_BR.utf8
ENV LANGUAGE pt_BR:pt:en
ENV LC_ALL pt_BR.utf8

RUN docker-php-ext-install mbstring gd xsl zip opcache
RUN docker-php-ext-configure mbstring --enable-mbstring

COPY 000-default.conf /etc/apache2/sites-enabled/000-default.conf
COPY php.ini /usr/local/etc/php/php.ini

# Imagem-Base:FIM

ARG WWWGROUP
ARG QUEUE_WORKER
ARG NODE_MAJOR=20

ENV APP_PREFIX ""

RUN apt-get update \
    && apt-get install -y redis-tools ssh git supervisor gosu zlib1g-dev curl gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs \
    && npm install -g npm \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y yarn \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# instala, ativa e configura extensoes php via pecl: redis, xdebug
RUN pear config-set http_proxy ""
RUN pecl install xdebug-3.2.0
RUN rm -rf /tmp/pear
RUN docker-php-ext-enable xdebug
ENV XDEBUG_MODE coverage

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

COPY create-group.sh /tmp/
RUN chmod u+x /tmp/create-group.sh \
    && /tmp/create-group.sh \
    && rm /tmp/create-group.sh

ENV APACHE_RUN_USER sail
ENV APACHE_RUN_GROUP sail

COPY start-container.sh /usr/local/bin/start-container
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN chmod +x /usr/local/bin/start-container

EXPOSE 5173

ENTRYPOINT ["start-container"]